version: '3.2'

services:
  
  postgres:
    image: postgres:13
    container_name: postgres-elp-dev
    restart: always
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=elp-dev-db
    ports:
     - 5632:5432
    expose: [5632]
    volumes:
      - elp_dev:/var/lib/postgresql/data      
      

volumes:
  elp_dev:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'F:\Comp Sys Eng - 4th Year\Winter 2023\ELP\Workspace\VolumeDir\Data\'